---
platform: linux

image_resource:
 type: docker-image
 source: { repository: node, tag: 8}

inputs:
- name: node-master
  path: node-master

run:
  path: sh
  args: [node-master/ci/tasks/run-master.sh]
